package database

import (
	"com.youyu.api/common/config"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
	"time"
)

func GetMysqlConnect() *gorm.DB {
	var business config.Config = &config.AutoGenerated{}
	businessConf,err := business.GetConfig()
	// TODO:优化错误处理
	if err != nil {
		panic(err)
	}
	result := businessConf.(*config.AutoGenerated)
	dsn := result.Database.UserName + ":" + result.Database.UserPassword + "@tcp(" + result.Database.IPAddr + ":" + result.Database.Port + ")/youyu?charset=utf8mb4&parseTime=True&loc=Local"
	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{
		NamingStrategy: schema.NamingStrategy{SingularTable: true},
	})
	if err != nil {
		return nil
	}

	sqlDB, err := db.DB()
	if err != nil {
		return nil
	}
	sqlDB.SetMaxIdleConns(10)
	sqlDB.SetMaxOpenConns(100)
	sqlDB.SetConnMaxLifetime(time.Hour)
	return db
}
