/*
	该包负责获取和初始化数据库的连接以供model调用
*/
package database

import (
	"com.youyu.api/common/config"
	"github.com/pkg/errors"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
	"time"
)

type DataBase interface {
	SetConfig(generated *config.AutoGenerated)
	GetConnect() (*gorm.DB, error)
}

type Mysql struct {
	conf *config.AutoGenerated
}


func (self *Mysql) GetConnect() (*gorm.DB, error) {
	// TODO:优化错误处理
	result := self.conf
	dsn := result.Database.UserName + ":" + result.Database.UserPassword + "@tcp(" + result.Database.IPAddr + ":" + result.Database.Port + ")/youyu?charset=utf8mb4&parseTime=True&loc=Local"
	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{
		NamingStrategy: schema.NamingStrategy{SingularTable: true},
	})
	if err != nil {
		return nil, err
	}

	sqlDB, err := db.DB()
	if err != nil {
		return nil, errors.Wrap(err, "")
	}
	sqlDB.SetMaxIdleConns(10)
	sqlDB.SetMaxOpenConns(100)
	sqlDB.SetConnMaxLifetime(time.Hour)
	return db, nil
}

func (self *Mysql) SetConfig(generated *config.AutoGenerated) {
	self.conf = generated
}
