package test

import (
	rpcClient "com.youyu.api/app/rpc/client"
	rpc "com.youyu.api/app/rpc/proto_files"
	"com.youyu.api/lib/config"
	"com.youyu.api/lib/ecode/status"
	"com.youyu.api/lib/path"
	"context"
	"encoding/json"
	"google.golang.org/grpc"
	"log"
	"math/rand"
	"strconv"
	"testing"
	"time"
)

// 测试article数据库模型，包含子表
func TestMysqlApiArticle(t *testing.T) {
	business := config.Config(&config.BusinessConfig{})
	businessConf, err := business.GetConfig()
	if err != nil {
		t.Error(err)
	}
	resultConf := businessConf.(*config.BusinessConfig)
	// 连接配置中心
	conn, err := grpc.Dial(resultConf.CentRPCServer.IP+":"+resultConf.CentRPCServer.Port, grpc.WithInsecure(), grpc.WithBlock())
	if err != nil {
		t.Error("client cannot dial grpc business_server")
	}
	defer conn.Close()
	clientE := rpc.NewCentApiClient(conn)
	resultStruct, err := clientE.GetRpcServerConfFile(context.Background(), &rpc.Null{})
	if err != nil {
		t.Error(err)
	}
	app := config.Config(&config.AutoGenerated{})
	appConf, err := app.Unmarshal(resultStruct.Data)
	if err != nil {
		t.Error(err)
	}
	// 使用得到的配置连接
	client, conn, _ := rpcClient.GetMysqlApiRpcServerLink(appConf.(*config.AutoGenerated))
	defer conn.Close()
	article, err := client.AddArticle(context.Background(), &rpc.Article{
		ArticleAbstract:   "hello worlds",
		ArticleContent:    "hello world,hello world",
		ArticleTitle:      "sb",
		ArticleTag:        []string{"11", "linux"},
		Uid:               3,
		ArticleCreateTime: time.Now().Unix(),
		ArticleUpdateTime: time.Now().Unix(),
	})
	if err != nil {
		t.Error(err.Error())
	} else {
		t.Log("test addArticle ok")
	}
	_, err = client.AddArticleStatisticsHot(context.Background(), &rpc.GetArticleRequest{ArticleId: article.GetArticleId()})
	if err != nil {
		t.Error(err)
	} else {
		t.Log("test addArticleStatisticsHot ok")
	}

	_, err = client.AddArticleStatisticsFabulous(context.Background(), &rpc.GetArticleRequest{ArticleId: article.GetArticleId()})
	if err != nil {
		t.Error(err.Error())
	} else {
		t.Log("test addArticleStatisticsFabulous ok")
	}

	_, err = client.AddArticleStatisticsCommentNum(context.Background(), &rpc.GetArticleRequest{ArticleId: article.GetArticleId()})
	if err != nil {
		t.Error(err.Error())
	} else {
		t.Log("test addArticleStatisticsCommentNum ok")
	}

	article, err = client.GetArticle(context.Background(), &rpc.GetArticleRequest{ArticleId: article.GetArticleId()})
	if err != nil {
		t.Error(err.Error())
	} else {
		t.Log(article)
		t.Log("test getArticle ok")
	}
	time.Sleep(time.Second * 2)
	_, err = client.UpdateArticle(context.Background(), &rpc.Article{
		ArticleId:         article.GetArticleId(),
		ArticleAbstract:   "世界你好",
		ArticleContent:    "我是世界",
		ArticleTitle:      "世界是我",
		ArticleTag:        []string{"linux", "macos"},
		Uid:               10,
		ArticleCreateTime: 0,
		ArticleUpdateTime: 0,
	})
	// 解包错误
	st,_ := status.FromError(err)
	if err != nil {
		t.Error(err.Error())
	} else {
		result, _ := client.GetArticle(context.Background(), &rpc.GetArticleRequest{ArticleId: article.GetArticleId()})
		t.Log(result)
		t.Log("test updateArticle ok" + st.Message)
	}
	// 连接查询
	result, err := client.GetArticleList(context.Background(), &rpc.ArticleOptions{
		Type:    "desc",
		Order:   "hot",
		Page:    1,
		PageNum: 3,
	})
	if err != nil {
		t.Error(err.Error())
	} else {
		t.Log(result)
		t.Log("test getArticleList ok" + st.Message)
	}
	_, err = client.DelArticle(context.Background(), &rpc.GetArticleRequest{ArticleId: article.GetArticleId()})
	st,_ = status.FromError(err)
	if err != nil {
		t.Error(err.Error())
	} else {
		t.Log("test delArticle ok" + st.Message)
	}
}

// 测试advertisement数据库模型
func TestMysqlApiAdvertisement(t *testing.T) {
	business := config.Config(&config.BusinessConfig{})
	businessConf, err := business.GetConfig()
	if err != nil {
		t.Error(err)
	}
	resultConf := businessConf.(*config.BusinessConfig)
	conn, err := grpc.Dial(resultConf.CentRPCServer.IP+":"+resultConf.CentRPCServer.Port, grpc.WithInsecure(), grpc.WithBlock())
	if err != nil {
		log.Fatalln("client cannot dial grpc business_server")
	}
	defer conn.Close()
	// 连接配置中心
	conn, err = grpc.Dial(resultConf.CentRPCServer.IP+":"+resultConf.CentRPCServer.Port, grpc.WithInsecure(), grpc.WithBlock())
	if err != nil {
		t.Error("client cannot dial grpc business_server")
	}
	defer conn.Close()
	clientE := rpc.NewCentApiClient(conn)
	resultStruct, err := clientE.GetRpcServerConfFile(context.Background(), &rpc.Null{})
	if err != nil {
		t.Error(err)
	}
	app := config.Config(&config.AutoGenerated{})
	appConf, err := app.Unmarshal(resultStruct.Data)
	if err != nil {
		t.Error(err)
	}
	// 使用得到的配置连接
	client, conn, _ := rpcClient.GetMysqlApiRpcServerLink(appConf.(*config.AutoGenerated))
	defer conn.Close()
	testData := &rpc.Advertisement{
		AdvertisementId:     1,
		AdvertisementType:   2,
		AdvertisementLink:   "https://xiao-hui.net/NewMysqlApiClient",
		AdvertisementWeight: 9,
		AdvertisementBody:   "https://tencent/video/11",
		AdvertisementOwner:  "youyu.Inc",
	}
	_, err = client.AddAdvertisement(context.Background(), testData)
	if err != nil {
		t.Error(err.Error())
	} else {
		t.Log("test addAdvertisement ok")
	}

	result, err := client.GetAdvertisement(context.Background(), &rpc.AdvertisementRequest{AdvertisementId: testData.AdvertisementId})
	if err != nil {
		t.Error(err.Error())
	} else {
		t.Log(result)
		t.Log("test getAdvertisement ok")
	}

	// update
	testData.AdvertisementOwner = "8086 Inc"
	testData.AdvertisementBody = "https://tencent/video/13"
	_, err = client.UpdateAdvertisement(context.Background(), testData)
	if err != nil {
		t.Error(err.Error())
	} else {
		result, _ := client.GetAdvertisement(context.Background(), &rpc.AdvertisementRequest{AdvertisementId: testData.AdvertisementId})
		t.Log(result)
		t.Log("test updateAdvertisement ok")
	}
	// 测试广告列表
	testData.AdvertisementId = 2
	_, _ = client.AddAdvertisement(context.Background(), testData)
	testData.AdvertisementId = 3
	_, _ = client.AddAdvertisement(context.Background(), testData)
	results, err := client.GetAdvertisementList(context.Background(), &rpc.ArticleOptions{
		Type:    "desc",
		Order:   "",
		Page:    1,
		PageNum: 3,
	})
	if err != nil {
		t.Error(err.Error())
	} else {
		t.Log(results)
		t.Log("test getAdvertisements ok")
	}
	// del
	_, err = client.DelAdvertisement(context.Background(), &rpc.AdvertisementRequest{AdvertisementId: testData.AdvertisementId})
	_, err = client.DelAdvertisement(context.Background(), &rpc.AdvertisementRequest{AdvertisementId: 2})
	_, err = client.DelAdvertisement(context.Background(), &rpc.AdvertisementRequest{AdvertisementId: 1})
	if err != nil {
		t.Error(err.Error())
	} else {
		t.Log(result)
		t.Log("test delAdvertisement ok")
	}
}

func TestMysqlTags(t *testing.T) {
	business := config.Config(&config.BusinessConfig{})
	businessConf, err := business.GetConfig()
	if err != nil {
		t.Error(err)
	}
	resultConf := businessConf.(*config.BusinessConfig)
	conn, err := grpc.Dial(resultConf.CentRPCServer.IP+":"+resultConf.CentRPCServer.Port, grpc.WithInsecure(), grpc.WithBlock())
	if err != nil {
		log.Fatalln("client cannot dial grpc business_server")
	}
	defer conn.Close()
	// 连接配置中心
	conn, err = grpc.Dial(resultConf.CentRPCServer.IP+":"+resultConf.CentRPCServer.Port, grpc.WithInsecure(), grpc.WithBlock())
	if err != nil {
		t.Error("client cannot dial grpc business_server")
	}
	defer conn.Close()
	clientE := rpc.NewCentApiClient(conn)
	resultStruct, err := clientE.GetRpcServerConfFile(context.Background(), &rpc.Null{})
	if err != nil {
		t.Error(err)
	}
	app := config.Config(&config.AutoGenerated{})
	appConf, err := app.Unmarshal(resultStruct.Data)
	if err != nil {
		t.Error(err)
	}
	// 使用得到的配置连接
	client, conn, _ := rpcClient.GetMysqlApiRpcServerLink(appConf.(*config.AutoGenerated))
	defer conn.Close()
	// 测试模型
	rand.Seed(time.Now().UnixNano())
	// 限定text长度为10
	defaultText := strconv.FormatInt(rand.Int63n(999999999), 10)
	_, err = client.AddTag(context.Background(), &rpc.Tag{Text: defaultText})
	st,_ := status.FromError(err)
	if st.Code != 0 {
		t.Error(st.Code)
		t.Error(st.Message)
	} else {
		t.Log("test add tag ok")
	}
	tag2, err := client.GetTagInt32Id(context.Background(), &rpc.Tag{Text: defaultText})
	st,_ = status.FromError(err)
	if st.Code != 0 {
		t.Error(st.Code)
		t.Error(st.Message)
	} else {
		t.Log("test get tag int32 id ok")
		t.Log(tag2.Tid)
	}
	tag, err := client.GetTagText(context.Background(), &rpc.Tag{Tid: tag2.Tid})
	st,_ = status.FromError(err)
	if st.Code != 0 {
		t.Error(st.Code)
		t.Error(st.Message)
	} else {
		t.Log("test get tag Text ok")
		t.Log(tag.Text)
	}

	_, err = client.DelTag(context.Background(), &rpc.Tag{Tid: tag2.Tid})
	st,_ = status.FromError(err)
	if st.Code != 0 {
		t.Error(st.Code)
		t.Error(st.Message)
	} else {
		t.Log("test del tag ok")
	}
}

func TestCentApi(t *testing.T) {
	var busiess config.Config = &config.BusinessConfig{}
	r, err := busiess.GetConfig()
	if err != nil {
		t.Error("client cannot dial grpc business_server")
	}
	result := r.(*config.BusinessConfig)
	conn, err := grpc.Dial(result.CentRPCServer.IP+":"+result.CentRPCServer.Port, grpc.WithInsecure(), grpc.WithBlock())
	if err != nil {
		t.Error("client cannot dial grpc business_server")
	}
	defer conn.Close()
	client := rpc.NewCentApiClient(conn)
	conf, err := client.GetRpcServerConfFile(context.Background(), &rpc.Null{})
	if err != nil {
		t.Error(err)
	}
	t.Log(string(conf.Data))
	_, err = client.SetRpcServerConfFile(context.Background(), &rpc.Config{
		Type: path.ConfRpcRequestType,
		Data: conf.Data,
	})
	if err != nil {
		t.Errorf("%+v", err)
	} else {
		t.Log("test SetRpcServerConfFile ok")
	}
	// business
	conf, err = client.GetBusinessConfFile(context.Background(), &rpc.Null{})
	if err != nil {
		t.Errorf("%+v", err)
	} else {
		t.Log("test SetRpcServerConfFile ok")
	}
	businessConfig := config.BusinessConfig{}
	newResult, err := businessConfig.Unmarshal(conf.Data)
	if err != nil {
		t.Errorf("%+v", err)
	} else {
		t.Log(newResult)
		t.Log("test getBusinessConfFile ok")
	}
	_, err = client.SetBusinessConfFile(context.Background(), &rpc.Config{
		Type: path.ConfBusinessRequestType,
		Data: conf.Data,
	})
	if err != nil {
		t.Errorf("%+v", err)
	} else {
		t.Log("test setBusinessConfFile ok")
	}
	client.PushLogStream(context.Background())
	// err_msg的并发设置和获取
	info, err := client.GetErrMsgJsonBytes(context.Background(), &rpc.Null{})
	if err != nil {
		t.Errorf("%+v", err)
	} else {
		t.Log("test getErr_msg ok")
	}
	tmpMap := make(map[int]string)
	err = json.Unmarshal(info.Data, &tmpMap)
	if err != nil {
		t.Error(err)
	}
	tmpMap[-404] = "页面飞走了"
	info.Data, err = json.Marshal(tmpMap)
	if err != nil {
		t.Errorf("%+v", err)
	}
	_, err = client.SetErrMsgJson(context.Background(), &rpc.Info{Type: path.ErrMsgJsonFileName, Data: info.Data})
	if err != nil {
		t.Error(err)
	} else {
		t.Log("test setErr_msg ok")
	}
}

func TestSecretKeyApi(t *testing.T) {
	business := config.Config(&config.BusinessConfig{})
	businessConf, err := business.GetConfig()
	if err != nil {
		t.Error(err)
	}
	resultConf := businessConf.(*config.BusinessConfig)
	conn, err := grpc.Dial(resultConf.CentRPCServer.IP+":"+resultConf.CentRPCServer.Port, grpc.WithInsecure(), grpc.WithBlock())
	if err != nil {
		log.Fatalln("client cannot dial grpc business_server")
	}
	defer conn.Close()
	// 连接配置中心
	conn, err = grpc.Dial(resultConf.CentRPCServer.IP+":"+resultConf.CentRPCServer.Port, grpc.WithInsecure(), grpc.WithBlock())
	if err != nil {
		t.Error("client cannot dial grpc business_server")
	}
	defer conn.Close()
	clientE := rpc.NewCentApiClient(conn)
	resultStruct, err := clientE.GetRpcServerConfFile(context.Background(), &rpc.Null{})
	if err != nil {
		t.Error(err)
	}
	app := config.Config(&config.AutoGenerated{})
	appConf, err := app.Unmarshal(resultStruct.Data)
	if err != nil {
		t.Error(err)
	}
	// 使用得到的配置连接
	client, conn, err := rpcClient.GetSecretKeyApiRpcServerLink(appConf.(*config.AutoGenerated))
	if err != nil {
		t.Error(err)
	}
	defer conn.Close()
	rand.Seed(time.Now().UnixNano())
	uid := rand.Int31()
	user, err := client.BindTokenToUser(context.Background(), &rpc.User{Uid: uid, ExpTime: int64(time.Second * 100)})
	if err != nil {
		t.Error(err)
	} else {
		t.Log("test bind token to user ok")
		t.Log(user)
	}
	user, err = client.ForTokenGetBindUser(context.Background(), &rpc.User{Token: user.Token})
	if err != nil {
		t.Error(err)
	} else {
		t.Log("test for token get bind user ok")
		t.Log(user)
	}
	_, err = client.DeleteBindUser(context.Background(), user)
	if err != nil {
		t.Error(err)
	} else {
		t.Log("test deleted bind user ok")
	}
	// 通过client id来设置和获取
	clientId := "1"
	key, err := client.GetPublicKey(context.Background(), &rpc.RsaKey{ClientId: clientId})
	if err != nil {
		t.Error(err)
	} else {
		t.Log(key.PublicKey)
	}
	key, err = client.GetPrivateKey(context.Background(), &rpc.RsaKey{ClientId: clientId})
	if err != nil {
		t.Error(err)
	} else {
		t.Log(key.PrivateKey)
	}
}

func TestMysqlUserLoginAndSign(t *testing.T) {
	business := config.Config(&config.BusinessConfig{})
	businessConf, err := business.GetConfig()
	if err != nil {
		t.Error(err)
	}
	resultConf := businessConf.(*config.BusinessConfig)
	conn, err := grpc.Dial(resultConf.CentRPCServer.IP+":"+resultConf.CentRPCServer.Port, grpc.WithInsecure(), grpc.WithBlock())
	if err != nil {
		log.Fatalln("client cannot dial grpc business_server")
	}
	defer conn.Close()
	// 连接配置中心
	conn, err = grpc.Dial(resultConf.CentRPCServer.IP+":"+resultConf.CentRPCServer.Port, grpc.WithInsecure(), grpc.WithBlock())
	if err != nil {
		t.Error("client cannot dial grpc business_server")
	}
	defer conn.Close()
	clientE := rpc.NewCentApiClient(conn)
	resultStruct, err := clientE.GetRpcServerConfFile(context.Background(), &rpc.Null{})
	if err != nil {
		t.Error(err)
	}
	app := config.Config(&config.AutoGenerated{})
	appConf, err := app.Unmarshal(resultStruct.Data)
	if err != nil {
		t.Error(err)
	}
	// 使用得到的配置连接
	client, conn, _ := rpcClient.GetMysqlApiRpcServerLink(appConf.(*config.AutoGenerated))
	defer conn.Close()
	// 测试模型
	userName := "xiao-hui-xx"
	userPassword := "womeiyoumima"
	_, err = client.CreateUserSign(context.Background(),&rpc.UserLoginOrSign{
		UserName:     userName,
		UserPassword: userPassword,
		UserBindInfo: "12345678901",
		VCode:        "1234",
		VToken:       "12345",
		Save:         0,
	})
	st,_ := status.FromError(err)
	if st.Code != 0 {
		t.Error(st.Code)
		t.Error(st.Message)
	} else {
		t.Log("create user sign ok")
	}
	// 重试构造错误
	_, err = client.CreateUserSign(context.Background(),&rpc.UserLoginOrSign{
		UserName:     userName,
		UserPassword: userPassword,
		UserBindInfo: "12345678901",
		VCode:        "1234",
		VToken:       "12345",
		Save:         0,
	})
	st,_ = status.FromError(err)
	if st.Code != 0 {
		t.Log("create user sign err ok")
	} else {
		t.Error(st.Code)
		t.Error(st.Message)
	}
	// 测试验证用户
	baseData, err := client.CheckUserStatus(context.Background(),&rpc.UserLoginOrSign{UserName: userName,UserPassword: userPassword})
	st,_ = status.FromError(err)
	if st.Code != 0 {
		t.Error(st.Code)
		t.Error(st.Message)
	} else {
		t.Log("check user ok")
		t.Log(baseData.Data["uid"])
		t.Log(baseData.Data["user_name"])
	}
	_, err = client.DeleteUserSign(context.Background(),&rpc.UserAuth{Uid: baseData.Data["uid"]})
	st,_ = status.FromError(err)
	if st.Code != 0 {
		t.Error(st.Code)
		t.Error(st.Message)
	} else {
		t.Log("del user sign ok")
	}
}
