package main

import (
	rpc "com.youyu.api/app/rpc/proto_files"
	"com.youyu.api/app/rpc/server"
	"com.youyu.api/common/config"
	"com.youyu.api/common/log"
	"com.youyu.api/common/path"
	"github.com/rs/zerolog"
	"google.golang.org/grpc"
	"io"
	"io/ioutil"
	"net"
	"os"
)

func main() {
	// 重定向日志到文件和控制台
	fd,err := os.OpenFile(path.LogGlobalPath + "/" + path.LogConfigCentFileName,os.O_SYNC|os.O_APPEND|os.O_WRONLY,0755)
	// 文件不存在则创建文件
	if fd == nil {
		fd,err = os.OpenFile(path.LogGlobalPath + "/" + path.LogConfigCentFileName,os.O_CREATE|os.O_APPEND|os.O_WRONLY|os.O_SYNC,0755)
		if err != nil {
			panic(err)
		}
	}
	log.Logger = zerolog.New(io.MultiWriter(fd,os.Stdout))
	// 初始化filePathList
	fileInfos, err := ioutil.ReadDir(path.LogGlobalPath)
	if err != nil {
		log.Logger.Error().Err(err)
		_ = os.Chdir(path.LogGlobalPath)
		fileInfos, _ = ioutil.ReadDir(path.LogGlobalPath)
	}
	filePathList := make(map[string]io.WriteCloser)
	for _, fi := range fileInfos {
		if !fi.IsDir() && fi.Name() != path.LogConfigCentFileName {
			file, err := os.OpenFile(path.LogGlobalPath + "/" + fi.Name(), os.O_APPEND|os.O_WRONLY|os.O_SYNC, 0755)
			if err != nil {
				log.Logger.Panic().Err(err)
			}
			filePathList[fi.Name()] = file
		}
	}

	// 初始化配置
	var business config.Config = &config.BusinessConfig{}
	businessConf, err := business.GetConfig()
	// TODO:优化错误处理
	// TODO:日志改进
	if err != nil {
		log.Logger.Panic().Timestamp().Err(err)
	}
	result := businessConf.(*config.BusinessConfig)
	listener, err := net.Listen("tcp", result.CentRPCServer.IP+":"+result.CentRPCServer.Port)
	if err != nil {
		log.Logger.Panic().Timestamp().Msg("cannot create a listener at the address")
	}
	grpcServer := grpc.NewServer()
	// 准备配置文件
	var rpcConf config.Config = &config.AutoGenerated{}
	rpcConfig, err := rpcConf.GetConfig()
	if err != nil {
		log.Logger.Panic().Timestamp().Err(err)
	}
	resultRpc := rpcConfig.(*config.AutoGenerated)
	// 退出清理文件句柄
	defer func() {
		for _,fp := range filePathList {
			err = fp.Close()
			if err != nil {
				log.Logger.Err(err)
			}
		}
	}()
	// 注册服务
	rpc.RegisterCentApiServer(grpcServer, &server.CentApiServer{
		BusinessConfFile: result.Marshal(),
		RpcConfFile:      resultRpc.Marshal(),
		FilePathList:     filePathList,
	})
	log.Logger.Err(grpcServer.Serve(listener))
}
