# 使用docker-compose编译与运行docker镜像
version: "3"
services:
  business:
    build:
      context: .
      dockerfile: ./business.dockerfile
      ports:
        - "8080:8080"
      # 先运行中心镜像，获取配置后确保正常运行
      depends_on:
        - cent_rpc
      labels:
        - "com.YouYu.api.business:v0.1"

  data_rpc:
    build:
      context: .
      dockerfile: ./data_rpc.dockerfile
      ports:
        - "5000:5000"
      # 先运行中心镜像，获取配置后确保正常运行
      depends_on:
        - cent_rpc
      labels:
        - "com.YouYu.api.data_rpc:v0.1"

  cent_rpc:
    build:
      context: .
      dockerfile: ./cent_rpc.dockerfile
      ports:
        - "5001:5001"
      labels:
        - "com.YouYu.api.cent_rpc:v0.1"