// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rpc_secretKey.proto

package proto_files

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *User) Validate() error {
	return nil
}
func (this *RsaKey) Validate() error {
	return nil
}
func (this *WechatTokenInfo) Validate() error {
	return nil
}
func (this *UserVcCode) Validate() error {
	if this.BindInfo == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("BindInfo", fmt.Errorf(`value '%v' must not be an empty string`, this.BindInfo))
	}
	if !(len(this.VcCode) == 6) {
		return github_com_mwitkow_go_proto_validators.FieldError("VcCode", fmt.Errorf(`value '%v' must have a length equal to '6'`, this.VcCode))
	}
	return nil
}
