[data_rpc_server]
    ip = "127.0.0.1"
    port = "5000"

# rpc_server使用
[database]
    ip_addr = "192.168.31.24"
    port = "3306"
    user_name = "root"
    user_password = "Cok774.."
[database.sync]
    db_max_idle_size = 300 # 最大空闲连接数
    db_max_open_conn_size = 400 # 最大打开连接数
    db_max_conn_life_time = 15 # 连接存活时间

[server]
    ip_addr = "127.0.0.1"
    port = "8080"
    protocol = "http"
[server.sync]
    grpc_poll_init_cap_size = 100 # 初始化连接数
    grpc_poll_max_cap_size  = 300 # 最大连接数
    grpc_poll_max_idle-size = 200 # 最大空闲连接数
    grpc_poll_max_idle_timeout = 15 # 连接存活时间

